---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.gitlab.secret: AgAHvKfE5J+bbwpqGv3UBuBXmce97BUQsCJsP6oovaq8vgiyJAs6KEzGrCnxIHbkcg50C+OjaOmKE0siChTZjkniQy+QVoXjqlFGGwT1vrPUsMS3jFxTYIUcEDyK/OdW+O+hY66fpDmqKK8juc0t/ynrfO9uQps/FZH4BB/TZjxTiUjxMJicUOMkb820CYLIZsTkaVm8uMvUbibbqQdPSV/yoQRlBPIN56RH8o+XSJaI+EtCwKvhZaPnLbFLNfGw6mUe612m/YEgy0Vnf8KfKdo0sR325Lvoo/Wsudj8MlnYm6GNP++2cabsdujmxvqXwdIk0CpAwBkU/siCKjEDYnseO30O+UGlXGZSP9x+Bau3/kJi1Qd09So4gMqLFsUhMB1yc1ovq2nRMXmF2Zcs2uRtFDcZpOBsphMEQJXIe1vb8yi5f9EPKMZrj6e3w8cIA6QnjVU2ht8Io7IWFpyWLUq+/nDETaks6gTiTdhPXxfiqobAL5aoruI9NK0hqUR+TYLEI3diNPNv6AUT1toJx0altG4vJQVljiXyWkqTi4ZWEW/Ppf3n/BRkTAO1l80o9JaK1VuIysiDh5cBVA9Eh0OhFIQTG40BkLXCv4YTzKQ/kkmUr+oM2bFxyLsB1CXSya1kzXEP+lBTL3vaZ7weQKv2jiGToH1pj82r+0udfowRxOHDK1oFCboYpni89rOIeZXuP5ntNgc/3nF4/tzAN9BH5S6ZK0gYUTgasgIHvCWVI/yv/QNKJ4U257rOiBuG4EUUdd9qQfYHGhqqr+XES1mf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: argocd-secret
      namespace: argocd
