---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booking-secrets
  namespace: app
spec:
  encryptedData:
    MYSQL_PASSWORD: AgDd8MD0FjFTFSw+nm0pHnQMvSsHi72V5EmUWdKSjJNoXzRCsuzkdnjLyzMQwZx+r90vLIm5ix7cq+MYAF+/qY0De03OxZaJIYlOfbqi504xsWwQ0MrxijbZEuC13hTRlH0s+BFEn+ThuUyGYp9J4RccdisTh0t9aFAeIKCz0BiQrVJ52pOd0RO9MFoioIFkElzcb9vCzKZzfyToZ54r+l4KsSWKo1HsMwMkjm9BUwUFy6k6HljIP9uWywfvshvHqAo2hkShcN0R8HkhwMdAmACULIjhSEaiwkZAia2vD0dQZOnG5VjrhFfi3kufoC3NCU17AC/IHqzVCsM5iAAEDTEKxS0vO0gpau2LPltMqYdHQ8ury9hs7L/tY1fKyIoSFXFmAE8IS3NtTppPyhGVlwEChpljB/JW8nlux0TvfIa8GU4vmasi2gu423pQM6iA2MklHDioaDYSE+k9Ghk5loRXgWYk1Y8KHoMHkCzoko6LLJMnnBgipmtGA85SxVd+uxwPLojvZ6b93j/+08dfA++g5O6G6R/0JFhc+vEBndkl/WAHR0KJwzsTeyLh/QdbChqDHYl1zfDigxHKCqaoGEAWGrVOIHX2sQ/cBRAEpLDPKxtFlh9xckrU3SbdYKGGLPlo7QKYLMwlWzsK9jUkHXLtPIGaneIlX0BfMQQaRXttxG+e/A5OUStti47cLHTBP0uT19ZCF4nFWsU=
    REDIS_PASSWORD: AgATmv35Qrn7+ETnjlJcy4PGRacycGtlmC+ZJm8WdoCllwwS2WRUrK2MMAlmTRCAJzoW4Xb3ZGR6+cziWcCk+djhTiw7tDjBCkuKz8L13afdV0KIX7q57QgxcOuqVDnN9qzxkuJbFwyjQbNaZKHMVMzDkpgJ3k/2zfJP+yXzxwIetEdRyFkCHzu1aaBgnRRSFadu3aKZYHppqJRyPXX5sOlu0pwZHUVbfqYfqv94+GewLIIqUiZqXCk3XSbCKwXcdlkOPQZQan2TdUTHFzg2I0JffKFELCpHQw2FeEeag0+4tWNbVr4crzq9S21nzDfUyzNV9go09Np5MaZL5dnIFvE0/B7S0MHXdj8c2knX2doXectsZtK6fcaKJ5TgL06krGsnK7Ya+Bt+OZTYZZs6rPJzGPlTw5VJ//JbK0TiZxGtE28bYnl+WKoxQXNKxOMGZT3oXU+lHxlK3Re08mZqCFpSnidQFcNoOjeU2RBYpC4QDZPFzyvd1SjNt8ZeF7mvkMfBfifBUBjqYJvwxC9PS/XGpoe7+fgBG29YrJnRB8jZ5UUPCmCylyguX/iqxH/8n6d30TANnSxcNneJx3RS/6x9C6vRTqJ1gBLgCLr99flfEhe1IsvXbfdu0bX3Y+YuLJxVHBH3ECF8oxy6JAAmBaQJ1Qv+O5uZhufM2eci+qdayX5EAhSVDkflX8JVrBZxgP6EMu92fpBeuXc=
  template:
    metadata:
      name: booking-secrets
      namespace: app
