---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booking-secrets
  namespace: app
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBKjTg6RgI45rXJUEIO0+W+1eN5PNcFAQ5dO6irWTxSAU3kCm9Yco5G9rR0HMJVs0XCMK1n4791ZPqRR19lQo/qwFHe+geeFIa9HYTw8SqWn1rg84gCTVS2ByfWFdxM1Wp/gpler1Df/Fz2wjG5UbClSYOirBeKvHdFXUcfjBe2p6mg8Zrz45jHEVdZVkl3OY2HRmGW0HzkDbwlQ7JeoTXDZqWGrTL/3Mb8GZjcNz2V6fiPTdBy8OZHUwr81OXmYhaTuCHPPIiumo5YpDxV3coeUZwox/yX4HPnXd3o+g3JJRMi2lQmLp4KdQaXsZ85oh04z18Rn3j8p++dow3KSas4dh7Pd99kL/wJCMV3oMcQe13p7vO9GpyDZL+UW7Q6kcosMd1Nr7wMurUHxHODUc8FZkUXAgWz6Ggo292Qnnn8UdiQt6Q0o5OMCwwzNN5PNs/owG+1kiRngk6TgDwPytFYazIhuo+laj747Yw5W/5C17j9/k+DvJWf9wNeQLjlpCvqy5hv2Ze4bJ/JyOeNjLGBrRJq8AeKHo97cu4zih8ItHK+o5+27n0M32cqBub1XNyrZC99P64hZe+pySrdpa8efxQrI7NMadfUi6JoHcJkcUYLgt8nBE626dchYOi95XkrfMsoJ0XAz3uHlRe202d8qJTbNjYU49WGpAovSx3EwF5+oy6jGKXVVKlGBX3j0EyriNGOp4YEfZtYDBVPs1rQWRUvSA==
    REDIS_PASSWORD: AgATmv35Qrn7+ETnjlJcy4PGRacycGtlmC+ZJm8WdoCllwwS2WRUrK2MMAlmTRCAJzoW4Xb3ZGR6+cziWcCk+djhTiw7tDjBCkuKz8L13afdV0KIX7q57QgxcOuqVDnN9qzxkuJbFwyjQbNaZKHMVMzDkpgJ3k/2zfJP+yXzxwIetEdRyFkCHzu1aaBgnRRSFadu3aKZYHppqJRyPXX5sOlu0pwZHUVbfqYfqv94+GewLIIqUiZqXCk3XSbCKwXcdlkOPQZQan2TdUTHFzg2I0JffKFELCpHQw2FeEeag0+4tWNbVr4crzq9S21nzDfUyzNV9go09Np5MaZL5dnIFvE0/B7S0MHXdj8c2knX2doXectsZtK6fcaKJ5TgL06krGsnK7Ya+Bt+OZTYZZs6rPJzGPlTw5VJ//JbK0TiZxGtE28bYnl+WKoxQXNKxOMGZT3oXU+lHxlK3Re08mZqCFpSnidQFcNoOjeU2RBYpC4QDZPFzyvd1SjNt8ZeF7mvkMfBfifBUBjqYJvwxC9PS/XGpoe7+fgBG29YrJnRB8jZ5UUPCmCylyguX/iqxH/8n6d30TANnSxcNneJx3RS/6x9C6vRTqJ1gBLgCLr99flfEhe1IsvXbfdu0bX3Y+YuLJxVHBH3ECF8oxy6JAAmBaQJ1Qv+O5uZhufM2eci+qdayX5EAhSVDkflX8JVrBZxgP6EMu92fpBeuXc=
  template:
    metadata:
      name: booking-secrets
      namespace: app
