---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBem3fWTQvRYVDRXb7z9AZi/Hmu2cbYU5hh8khm2CLLglBEJrJbdfDn+RNJUREoQu/fabxKwchPkLFMFe6PV+X3Rwy9NEWpIYKLY6fJRAndGU42Jq940Y/v/dbN1CitoBxbz4vhqcHIzPLtv46tAyX/RRYKUYf20YSbW2zKY5omtZaG+VpTIT5EjSmXctjutO6lt5pJfgLlS+Wao6xg75ZoNkBUk+EIqYOEIaEddIhdvn0o05PRwj7ELdmby8F0UZUgDhIYF2lkessdmw3LBKSolkc/X9S6Q3+FrDV8ib8UFFhFZvEdloCBS8iwLWZnyk6UdRTfYVu2s0iXxHSIvXXKmPxWDAurFRqx1QBCs2P6VgoqaptrEZk0ogTDKxUzZNJQcOCZNFTempMkcuJC/d7ZMrMCRIndQH+dDZlG+/xVd0cbbY/AdxzwAM4J3gSYyApMPBA5DDLyMHCiZ02cxgzirFYbTH2BmQpvtr3kc6j5SNwCB1GmEEEIZ2VBj3oyWBH+BmYxpoC3SCyWOMqyQAQZ7KhQuIOMLLRBbXjyq1AZI5QxUIrgxfS8y3XvdMF9+gllXPwKVJqdd9H+1P/sT8v6zs16TU/nQhEZp2KHV9pQZl2C841YGdtAnksChDzK+FANQ7qgLIBxtsPJnlJUymu5554cI9HHs0fSx8DLmWMyuE2XH/jnHHicm/p67hC5wAfeRkY+JDeC/HMXa/1rOgHyoiWkp2ZUGZQa2VH6zqHRCCZ4qxMYlAhJ2nNso9loBXPDhAZ8uA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
