---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry
  namespace: app
spec:
  encryptedData:
    .dockerconfigjson: AgBWzqXSluBOL2yUcNqt2666YT0Aker1C5toR1iXlW3zPGm3SgIzASesT6XiZUsob28JH559Sx2vJTZAtVyuyeuFRr380eGrJnsSffwvNTuB9XjBjlHkvK6tqJyNlVvs+81UEBddJnlqZ9FI3IU5Q0QSf3oojvnVY8n2lC1i64xkjf6xRUXoF4VYk0Km8dbIJdMAfie+ymqUgpSViFDsreZJ0lCoT+H+1tq4y7tvNcPmnEiyLNuUd8wqDCIUvNXuz0s3hMmCzZ0FNVY+vWdtaQtICTMfCVqMoNSVz++nPxsb4h4km/VbCkdXvqBojRYiTBYqcRKdLsMqgalk3/AF5yiMjosqbqmGNy6Hezy72OtrwjBGaWSc6gf5wdr/GMbdA98Fr3sWiRmOqZa7guA/g66KOVO3jyXzEcSaJTO3uAD4+CKr5stCgvImXERrHR05wM+Q7SVLmotsptQiVzyJKj5L+2x7sRAa5N+zjwGUVrmKckouXLms8C1+OhQmprmg3J9DqKASdMs6WIQ+wvaJluIGAb56PNIz7EGVagx9G+QfQj2gSKLWVcqw+X4EggXmdEY+nPw+JkdEBsSWBhHiLLBROnkauEAu3El4DBT993tlciWUqJK/MnrYGfarlfTDZ0ZYtl4ftw8EaSoUvZS+txUEoZxu/QO9Js3LF4bzqWwWVK393W5DIewK8OXc9VkyJVyUXMInIsthPQb7tIQy0pqrJ7x0UZdGUXe9IXbhHJXGWqEbv/BkkoAcEh1fLNdhJ1s04zFPwA4TaN6v7DSxsgdeKDK/zX7MkczUUrVB8L0qtLoloLKKEUn9EPzFeoFJmCXTDST5NWFzOeej+gD42qZSCo92WiA2r0j+C31vuLzeWYPG/IGt7ABRnkwwIPWKsgQ6+r8OoPsIRLDGwhS2UhALa8JP+htUVmI27lsWNSmycAorW1VJyQ==
  template:
    metadata:
      name: gitlab-registry
      namespace: app
    type: kubernetes.io/dockerconfigjson
