---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgDWMbd5r5T/pP9QNSvBkCKJptp0U/8qg322fYxAnreldN48CyOWXXwRMI4QIqiEUN6TQV0I8xf0w1yAC3rxzahUmUWLhnuyosoYkHMckg8AGqBpRy+5oZRlEFckqV5qaRhtSayHePXxWSm4x2RpqL35655JpJ6cZPRgsMgsqJ47MJ2kR3Nqot9Izgij5WJUtc5+cnIRpYqcrr5JCBezlXyG8/AVrJdPjja2yNlc/kMuIwP8/MFLfV0xqgVQA5mAmomxpfDZgvWtxMdQQp2ywg352+gmyvnEgGlbPXuYFkbybAF6EiIo9TM8raujDmwC5jXBbbGFTHEmyQ30hLiKvOmv/J+R3qAKpicP973ag2dNPG4+pEtZT9kEmgV1uBHQgkae5tfBbntT95irCixeCmMH7c9MdX4YeaGIX5woWLqHcgPOH6svORVNi+3BxZK7yDTf7JWP55fzPa0M7NHKZqtr1Qs8QlJPiOiRDoAwFji9tI5PiEcu/e4s2OrzyarxXRYQDN15Yo39ymkbL9i6ZZZr0JAwFwRB8eUezLUrKvB2/uTpGDjPpd8jPETsyMygKUKa7GbObVf4gLmC1kAxwrew3pmN8zchxqJcCMMd5bG6JyartOQZl16/cMbPB5RXpQ1YOF2yIPFrTC8pDZZVV3vo2Uz8trjPEuiRRm/gwjSywNsx6YNAxEjfBkHD1aBtAqDZD2ZHmLEoWIk=
    admin-user: AgA5yKMbhXDThY/s2lYaqOY3Qwe8ZQBt668E8NvrPzF52SHFj40dfYz6JhV28nfvicE8/u1ZDSY1gMZrbaOEMb3Z39dGtQ37Vd7t9OFmvOAKDfaz7L/rDFWvY2fc8kfqBzWvlM8jg9TCpUUrkZvwYQadxeems4n1FV7uZoRoBa5VuORUM3aDU2fB+hpOlZWSaD9BBnl2b9xzb4lDWhQP0A28hebqiKNa13lJTyE29h35laq3Vf24ZWN500gL6SXYqbm9Wsl44iWwfWiyUxqaLd1DR43JkR02jiy+QTbdoXq0FM+1l27s27MZ40MnPCIN3MrfodYxt+DSXJuLQiD/eUfXuGOKL1jqGor99Gl+mv0xZvNwTIXYrpfRRpXQAhF8acIkKL5B+Fa+j5UKo8AgvcAPHJeVdxM6JzISeUfTYvAmCQDYc8BJLbzfr4+bvtxbvoqdRCVd+rc/RrxrN7JvBgJIibuyKiNdxoiMwWj/zhojgUN9PaoA7PMVXTncm96WB7wSj7irvxDIsSczaplGuZ3C0Pgk4dL5rOAuGHg2uovsElnhx9n4sp/NxWY3s8Wpc+6toFoejJboVmI8S+ugXXVr/eiowy5k4nffyxUYttHNRKjPd00SQWbYLLjbxwLjKtxYswvgnRCrcsum2KO/uK7HyNHl8P4LtgrTmaEriYiOVtOUF+woiVcNQ+sRgy532FAo0mpwdw==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
