---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git
  namespace: argocd
spec:
  encryptedData:
    password: AgBlYLFNwDZLT0W7HP6RyL6mk3jHTaln46udlYoDYAXrs9ay+1CD7PZNDHK9+N6jXNOoeJ/1/eZwnbsUvZ+G1HetSrFWN3fl6nIYbyiTG/MFZ7KJ4AtuAyawWoW4i5LDOnIm/svL/8sIsrqAlx9cLcuWRX3y1Q6IfSy3fwVVEqBodaO9fFK0zCj6HRmzTMr5W+k44BZy4gLl6ZNyqwfIR5DyT2SK6hHTsFYYh3LWWU1oYv2nm+cfHQ11D0JB5TDeuuRVLMb482Q7nAfrtxh2GTY05PcGrYBQJBCP6PJlHMxPMoV/fp2zKBZ4SRFYSfDqsPWLGzmg4LQIksOz3X9j0QOh4VD5nsP/NfNbfN2mDlITsuUYdADR2SbymXq508QelDRx+n25u9ke2pXIvtYJiHEYq99xe00AX7fOH4nkB8zv8+7gNGEagmXSMf6307+o3Oo+GeT7zHQ/0WLaOxc5mXaN0QfS0l74KytNUjtzyFwMyfMF9XjqcPM7h4xEH9pQOhouA/UepexXzwK4ab7bJ6Lvfk7EKm+GJLza6V1gCyqKhLikLc1OnGJWIWev1XXzuqlfkwFTrP9e6qkxGzDHoYygTElW7ElMlKJgl/r917lnbDGPv6MV5EP24yqbtAvfk/BRqkmuTS/+sTtGzQ2ftnRs0RMe4gyXz2tjKIGFafGO1sUBesCXcEjsh/BGB0NOvxwOQxNCn8KG9NmQUX3fni1Sy2KtqQqJ3L81SmfvHQgdkAmjK1CyQ4/dbn6TeJ7ejyrzOg0=
    username: AgAnO7hij6BrKbcFdkibb+kic1Oo/P293UaxGUIsxerMSANYs6m7lJPkcylvjfz6cFEbD/PIcsApyn8ZzbobYNWLAhXx7uzbQ1Ej5IuYH7dSiuerVF98FoEhyt+rPekNt+iIXs503U7cLUENMkmin18m1NMMjjV6FGNGBalrK90owQDbij5lpRIWIp/+64KAQYNFznkPeVk5MeeMC6LZ9JIQCz6OMS9yZlGUoOhGz73DnJW5nIGttIFtwJAbrbYit06ZO4mo1UGHbwDHmIEsMUetqpnVi+59GfCcx7ZLPU5xJX06zLfa7MD9jp/pMOyQfL1Vu6rtKR5CWdCYLVoel70WbgGvw1awxmgwC8sOYYMxL/jVRPpZ3B9aQfpsMco5Gd65qpOYOyYdTXkBY82WdvTdE2xS+42R+WAa/ii1QEhJavltj3Kdj0UkLJALkztJdArzwy7IAz0XtCTmaBhqfe2rh1KPniQtn3vBQGKqoh+e8K9iHm2aTPJvKTa4f5K+IgLfyJ8TEwV+uQm9b3MqtPBNkQFZr1WoEZ/o6ACEvNKJdwadSlItBUPCKO2v8l1pD9yHAI3ivtu8IWy98dpYtikC4ZXLpPV62TEbdB5CxBmyxHnEuSEfY4756qzKVpYC9FuHG9t5yfjr3dz21sbQdgMqKyvMUFdFLP/loG28Wu28tATW7s3uLmL/VNjfuc9sOOZqkQwJlQGPE3ZctcMUBmVfTN2RblF0How=
  template:
    metadata:
      name: image-updater-git
      namespace: argocd
