---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-registry
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgASoP6VC87JmRju+ngM5BXI5+7rT3C8CXFkW+mcMXkbBAqFVAPM9V8+QJxXa3Tp2pC1SpbObJJRMguZOD2J8L27VXUuLS+Vqpt+Wphponl0aX1wieEJO3/hfVdmIbf2dAIkBI9r0KULrX0H2TEZd/sjVDMJu/MToq/xUP9h4Yb+tPFuEECczcZ/zyrQIY/fB5633zpPVCaQBR6rFpzdEv9A/4Sp8+gNU5DHoFmc+wnvrjgL1TrrWQP264H8ik678YPhxguToRAsY+fx7doUTpvLY9oCqeuk7RH6DT/Jqlz9lbxHs7xpKF5lDSCfqPXJnooTgzUyMqvgInzkWEGREcIHvPHMvz2l5A2e94hLC0nK/QHSKWDMiBwDuWxzTjLeey+Tz8xitwExlG0nJx2ukzccHn0kSev+TmxsSNpzyQLnt1/bU5u+zTJ8MyDMvu07slJrQmBeXl2AGxtBb++2XpA5QJNxQLvM/gRGdhlECo8L7ilRzsiCc/2uXsNg0ZeJM0/9T9AMb6Q6xcLpSxfkIEEAR2+KDedQqHdRiV8jhFPsw4B4HHiVYg2mXq6diShkxV1s/koJkZkdHUQDUhtR+qzlDksmujV15xlXeFBl/7CUlSUc3hhpCDEfpk5wzeyy54EKd116K0aHq6tKnDrVFfrgHsGDSb2ghO7zRBmOiNDD9zgwO5a60fNhLUriiuPpIouLg8kqmRsmXjacVDeCFoBkUXkLW8tVcHdjKdh7iOrXvxAU02SdX8upWC2UcEJokfI0U9ahAYQancOA2A2LA/ITfDtnM04IeRQazp5Eph5JnMDq1y0cKWlKEVM/FBj1eIjOi7FVy/BEeWPiJGSTeqUFmH5noLc+1eoq3ylyjdjcAq1iHRA6pUt+XvAAlsaLah06vh07yONf+nXL2rQHaxIc3L7oIamnCewG3+CyeN+ueIlbUPaMXw==
  template:
    metadata:
      name: image-updater-registry
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
