---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-lgtm-user
  namespace: observability
spec:
  encryptedData:
    password: AgB4KCrsDhl3JIcePjIFce5dclytE5LjsBvMqXnMgjdIVqQUxHZYj4WcDRWJZke0Ed39mdOhRrh/uVED1/kgPFkfaMkxOaicSRiaUxhajmii7KDSgT8E26/UrLzK3dhzDYBG687h5isK4B2rNscDcq3Xw6j3icXzH/eGq/Y2GCNCivQTdfqQ3Z49mSUMxeiAVdsUfXBWgAkk5cIhQPc65WLDNlH5f2HowX42U1UTa7MIax3uMevbtXp43lEnA+oM27lQiHa+0DhgrR/iZST40EqYC4eyJAcKGJ/CrUGfBnLp99nv+e+jwSU3ssEAexTZG+p+9XWgLzTb62qyqGQddZSJ1Ho1/Jbk+UBJCu8URexrLlacco7XbtwzS12teFQxewYuNPow8KKUJFYx9Icu0Yx1EVixB1wwil7unmXzf7Gs5M4hWufjX3qtwPgyTQ3IUtyejUW32wbqyeXBL5u7QlF6mobQnm7fR9ASc16Fb1nWd2aq1LEdS5SdK2AO3n7b7NW4E4ao5qMtnl/p99709bezYEF/FJqh6WODroj6YrIofAbsQ5/LLfX6mBwoaBbNXFM9g/mdBP0/rYKO9oIVo6IZxJcFI/pO8LmEcdizGxrZXyEl2/0CgXgQqMQGcsEqnq58QqCgOVzkmP5tWtSirfB+zspxvifJiCS0xLNr3bWOXLNNH/qMVrnWgicZvpPVZO3kkLfhGtT5LU4=
  template:
    metadata:
      name: minio-lgtm-user
      namespace: observability
