---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: data
spec:
  encryptedData:
    mysql-password: AgAhY7W5g35ffi/lMMOQ7RHk3jOMaHhVLKjdub4Apn+n0e55HN9Taxs+CLofy9cH4WS2q/qhVFzorG1HHpsYmyYZcgZ8LM0lFXxx9ic5t8D740qwjOlGrwC9cERVzawEOS3dmMYww5vFSNtiYmXRAt5h0QEtsc1iMNJVj7wsGbfujxwlZ/o33r9phllyC49uM4B5C6yXyXvZeIlttf+3M+Hi81gnyNjigENJzm5P5kd5zqQkXGeeuchPDmsUGREUwuFXWgO6EOyMouUbSjF7iH76Y47/XPVFewbWOWzQbK3nlU6HUBi7c0G+QOncCHko4Ofsc19RO8y3iy2LYXnywdyacxzMwLXKeus3DpbB6+LEX10yLxWGfXPoog3eBsin2ToNPolP1Rn7CSz7SdyxrU/yt39SCnUSDr0Ib23CbrQ9JrkGXyQ3dPDxGrL+zibkrFvUO4e3KeSX2DHghJYnnGjQxG3w9nSKrcRM8w7lfUXSNmjH6Io49dizjV5JB8DOHhc9CmE1MjnIIuGTD0S5u2BJzdxme3dSELmEeJxqBkzVO4fEqRDVxkZLmtyI682BPalf/pP2kuQ0qTuhPvc5EuIn70okZzuK8WtGUibMbeUhk9L8mdJJDehYPi3oWANqAb8Xkc/pb1tR7zJCAr24+6GEIgH8T/rGzJYWOfgM68tOD6XOeMHASAwNz1wiRZCFIHAWG6appVUkdshfPXwuzaGmY7JluQ==
    mysql-root-password: AgDAC008T54N/CqvodE6oaV++8XINmyXLLbHdeESuUfaZuMKZOv/Qa6Ocoqdxt6nsInirZ42zQo2f+cHoDZqidnD5tJpx460/CFE5iPni3nQBWiSLe8mgZHDl4OWvqRtndfNtudJS0WyoHt42sMXkGsDmwOFCROtKfpBE64BQ1RpR9tF7kHerIquLVsurEzjdQoZOaLhiBQgHCQr8pLu+k/50rK3N1fvya0R5hWV0rancTcLj21Y+HmSDgQGLm+muHma4E2BXZaepaTinPEsjgEDB2mDfo250WHiGzksNVfVi5udRcIfuT1KeBOtHRj7gQQFYde4Y6EUBPx30KZOGn5tju+lMl9xj8Bs2br5wAn5kq7tNOrklUxUfn94fQXHHtQJT4DezMcTqnorghJ7GbAQuUbk1ucENo3kTYvQ1WnCBGl7gkTSmdjBK4/ln4Sf8DHFNUqT4F+FNEMIOUOqF45CrqsYtxOFmsKDRLxql+EWxc8icpa1GYMSXUdgY9GVtwksEPwDPhc++Y8gnRaeq1lBgzfbvQ9asY5dR63bB5X7TClqrR7EbDB4Tb4JgKqA96K5uIUXtXV2rUO3eZ2Rr0Z/s1txzvjlK7U4K1K9CWXZWAoIVpMzzRAAo6fk1/vVljoG4FFxfDP8BffzvOwJZtyayeF9D8SgeZGNZTpoTLHo/yquxHzgGcLpfhkLbbEUQ0vBkBJEFl3NiEM=
  template:
    metadata:
      name: mysql-secret
      namespace: data
