---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: data
spec:
  encryptedData:
    mysql-password: AgA0pYHaKj5faySO/Gpv80Ef/bMziUBQrhgvrFMA7iuNtKXYuy1Ett9PsZ9+rNSdu3PATdxccuiMQiRY+5Ogy/1Dwo+3I/LP6doO7UkVIQXUhzvI0lap782DSOjwqJfL0cDzzfdscf2TTwi6uCpmLKzqdYQoUJE/EnYg7bYLun5iUZcwfG7zcRlwZOceT1kkrB7QCXxNF1WAuAw7MWEIMmFEsFL8XlHBtTTYNCxmODWBpsb24zyl97Ut8Em1RhjKIkXu85v+fBiRsZ4CPJso4qYcMROtNc9NhV430sJIVsbMDuHAD2wK40XvXlQ6A9aRgv4p83nAenCqgXRN8HHRRoXlGapoYUSDz6OW/QXcQFV7XqQwtywZgPKlT4zY0jssZjs5QojtV8toifKzkfBtDvpK5g3yog3b4YLGwVUtg4nvtHL8WKksaC0l+OPu8bAp5/xT3eIBr9BYfYdqQJF9U86XFF5uwS/WyD/xLJpgkdbCYB2XcP3DVR4RyvZjdu7A2u/Pg9Opolh2kppNOZBdHS3InVUcZG+uHnVQuFDhJTKG9M24PqlFvQ6+Ek2tbYZnJ5xbmvmthCSFIe6oUS+baJR1lnDeJdsO8Q6rmvXow00sEttDjyos5eaJzIwMfCiMm1DKq1F6a5Q2tU/g0qHZeGJevpFOM8TlsFS6klxYK8+VPvco5NW6piGCOeGqY9stgq0QRqhw/Jb0jhk=
    mysql-root-password: AgDAC008T54N/CqvodE6oaV++8XINmyXLLbHdeESuUfaZuMKZOv/Qa6Ocoqdxt6nsInirZ42zQo2f+cHoDZqidnD5tJpx460/CFE5iPni3nQBWiSLe8mgZHDl4OWvqRtndfNtudJS0WyoHt42sMXkGsDmwOFCROtKfpBE64BQ1RpR9tF7kHerIquLVsurEzjdQoZOaLhiBQgHCQr8pLu+k/50rK3N1fvya0R5hWV0rancTcLj21Y+HmSDgQGLm+muHma4E2BXZaepaTinPEsjgEDB2mDfo250WHiGzksNVfVi5udRcIfuT1KeBOtHRj7gQQFYde4Y6EUBPx30KZOGn5tju+lMl9xj8Bs2br5wAn5kq7tNOrklUxUfn94fQXHHtQJT4DezMcTqnorghJ7GbAQuUbk1ucENo3kTYvQ1WnCBGl7gkTSmdjBK4/ln4Sf8DHFNUqT4F+FNEMIOUOqF45CrqsYtxOFmsKDRLxql+EWxc8icpa1GYMSXUdgY9GVtwksEPwDPhc++Y8gnRaeq1lBgzfbvQ9asY5dR63bB5X7TClqrR7EbDB4Tb4JgKqA96K5uIUXtXV2rUO3eZ2Rr0Z/s1txzvjlK7U4K1K9CWXZWAoIVpMzzRAAo6fk1/vVljoG4FFxfDP8BffzvOwJZtyayeF9D8SgeZGNZTpoTLHo/yquxHzgGcLpfhkLbbEUQ0vBkBJEFl3NiEM=
  template:
    metadata:
      name: mysql-secret
      namespace: data
