---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-s3-credentials
  namespace: observability
spec:
  encryptedData:
    S3_ACCESS_KEY: AgBpVHTxc+YW/Udm7kqWaFCTYYSTYnhxSR4M8zyHarxNcFGM2BP7PozToe4shKkzrzPkmaSaE3CTYeeni5K3DJHd2/2QL/OGZY7PU3tKTDZSCmjXCFFwEcg/WFKpYuI3icUPo5sCsmgHvTfj9juyjywksy66A2xrzUzlLaQgZ+hyatl1M+iiOrlDFJdGirU4l/GU07GqLGTGjclinYwHiBh7LYcviHttSOMvm3jZh+dwM5d+lj+FvoJTcuQy66EnqaLFDTYajRpxYQ/QWVcg6RAXZpk+atNNeCken14o9Ukf3ooxpn+SJcDgWFMBNfttNpxuD8Mf6FUwyC0Oow9DT7u9OEoBNjakHw8L5vSDz0rRD5h00xeKq1pqtVvHK+FcwCkUyO3NQhyOP5nV0Tn4Ta75GCuSr5OiGh8IAVjxQRrc/qSldcsF76CFBYZZzBapQQZLCXv43drHlNhFfO2bYdZUtbiQIT50C3Djb9uF/HR8KX6hH4t9gavhoPrFqK8efG3k4x851iLUTdSvuk1VlJN3d4eMEHRYuCE4+pH8CMMRrSYYZ3lM7WCbsCkFWVpGACYehL69oOL++lt4aiYVAlu9viiUgxL4emqgbqaJt74D4gBM4z3xBtB79Bl0CGzNwDPK/J/eccK5UcK4wBnROxDqyrAs9g+HEd0vyRz4IHMb9w5eUXuyGoNlP1/9oVP4L1S1DfKP9f/QYL8=
    S3_SECRET_KEY: AgCqljSeagcGYtGqtFScfPUOHBayPJzeqHU/qKay0aKS7p9m0yf/pqAwjldfD5xkLG/PtObJX7LR9JXM7b+PyPE8xwcJdoyVlRRRlIl+fBSlV5yeavpBAEs1ns2EBzr2GllN0/w/UGQbhFDPai0YAl/CZlAvBOeZBKcMlNgRaBbaZjwzvDm8XrFyL4ERrHRumKpt0vmhpa9Xm9DXdIKOyfivpHuJj99TBnnFevmsVKisnrrUgc0xjFUBZ2SYBWP/1SUAes1gCuHNehB1VWDR4YVlL+FcM65gUaGjBmSFkFJ5xLSG+9W8guRabbWff4uP9FDZRYNXJYIUFtIarwFl+y7Fd+BnooDu3H0ehezj8vhlEjuN0ipRAHq2Qti/uNOVNjkvBb88wB+arYY9LDtPSyuqjOz0waPTa8QK+NOsDQXk52oNCzqe5Wkr6IrKyUfv5X8IGGojnJ4N2bNR3F+bgwhYQ3/1m6S1rZSByu5ZpKjIzKFheGTaofEQpLkn4XZolc+10HbVvIrCSSuTMLOcS831UxiQjQSI5CwNPUjF3GDKwQLs0/JMOunSaYwukpDt7Vjo7p4SKH9M7Ta1aWDVDoIG3RmtzBGrzSR4iI/Va3QyDSYMcEXSOVA+KEiruIeDKRQn9ETlz/1zPqq3aqkfCBnWtvB/rqupadEu0N7dEiDWG/TeJaAWcAkI5HAUE0XrSwrpFKGhfpg1cys=
  template:
    metadata:
      name: tempo-s3-credentials
      namespace: observability
