{{- if and .Values.metrics.enabled (eq .Values.metrics.kind "PodMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "app.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
{{- end }}
