---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-admin-token
  namespace: app
spec:
  encryptedData:
    ADMIN_TOKEN: AgC5WNcJVr7MlC11YMj5oohuo+bXSFizOKnY9DcseqzCJOESeRn+oiMER0Edl5wkKb9JXS4DlQd5vLqOINMrVIGfPQNimlZ0s0I9pSxZhtw73RxupuNPVLmNTJ/MMsSLa2DdZYUHEVaVlC1peon/hsS3o5FU6WmPtV548kXWILmYA9L9Ta26zIYJ6nDmw1TaCvW4NYcSbL+pAMi3O1Tvy6Q+YMif+REEBtM6zF6BDjCNrVugX2O5QQV83WG5USf0lSC9h03uZ/bqeQViSTwmt0cnq/M+jVVYugF4jjBHqYNyDFFOfw3Fsx9Yz0C3xvxTJCHxWX0FfW0dnJku7tQUIPdNNt24/aUkUU1JlYgy76bufd7njTlKrdk8ptvsvRahl5uLFIXVRNsBHaVWdstJ18u8duz2wIdHZsWebzvTQvCZ8fA1wO+ICTUz+U4lBqB1517ZTb1sQodRU3SGI6/slL91xJFIVaL9LEk1WR1pR1CeNtoapePcWys2ZpNW8/ZvEYMt3MfBcyXdNrf5Nyrv7jBZf/d2fbqT/HUUWdN1a0GS0TOrQfoI70E8/9uvcUoa7tDvzsTxN9hoTeBhDLNUPoLoUwQDMCtPhXWv9DNC5dp27PpxURTxkE/usGselt8f2NiZxzvT0MZ1iZFk/3HqTW9D1kDLXcMhLG7HvwgnRFbb94Xpc5G0GAuquVJ9/pe4NTwfdfHEGZbD+/VT1U84bVeQVcAMtiGoGpSmN+LAMoj6oAmGXoYSgbeWCuG1JzCLKgE=
  template:
    metadata:
      name: app-admin-token
      namespace: app
