---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-discord-webhook
  namespace: observability
spec:
  encryptedData:
    url: AgAF/PP1+DAaOAqQNEULzUbnUo0H+OIrCHJrfy/bsAj5f7VJovKvkZI5L3EEcq2xgMmJSl+oLkCr8JO2aWdUFXKYa4ORYWeVdFEKs+saFmJmWLw139Co+vJFjBG2tpnV5aWsO9S9h7Zh2gN6hDQXcm4DoMoqia7UJFLDycHqOCJ6IFiONHtl5qQ28GRN4FDq8FX+fjEGgCWCXJoxrPCW5OF+NH4ZO/ivVvqmsRYmwXuaOxQnVkjMrYADQs0OWz46xk9bTrSeP01zg4m3FgdRBpOyueTiUbCbK0g/gwFsRp4ixGd3EM24rP033LgkYYSrYtJKuEP5i9YYWHszqtReZdowWDOtu+uhR4K/qLSsogVvvyqmr2Rsh8PkLCQVjI705Pw4rcE/wybB66s/qey6yHPhPM8m8EeDs4lsdeaIeOOhfYj2qqBOvdU6/UMKk4iTG5/v1k1xpSuVVwSWNH0GvLsmSN0qi4itCzsB0kLd4lKzRLJwDVkfgiFGPUFWV574F+6wV52xN4Tz/V0quczwDoVmVOKclb0aIgmc1xbi4SH0hXxwQY1EKs6c9v7AqV1cUP5sfDvZA7YZrlLO2jH9snOsIGljl+CHf2vFa4RTL2JFHde9npypjlSM6Z1/z1hSUdioKakaT6bT/2kT6f5sY4YG6RPVOyIUdCHwH+8WY0HoK17onIrVlyXodP1qaqFHl8qjhw0vi9WiEqQwocivQ3m47cXvgHdcanACjXVxD7+5s9u9L8QdPvUbzveBbdIacT9S4cs1k6peHsXes7BHIog1x0+irtwwmaQKiinhJ4zfCZV63nusRRsGe45dDMlimzGbb8gpbZv+sImLgMxfspIOTHb15xaN6ceE
  template:
    metadata:
      name: grafana-discord-webhook
      namespace: observability
