---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-ecr
  namespace: argocd
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCj9cisdN8Kln5pXGEOTfeuX565kMVxu6bt5/OlpGsFcTQIevzD/O3kD/dV0THFrIObzRmk0CMPjUbrJsxxuZpb0a/8VpRN54A4y0uRFZlL70XkQU0gVb5/kqQ0L8X0ITdMUpicL1v3DYGPXDUvqFFo3WdPhxMca2a3VlqoUQ2SHX3W1EZAwpjqyukmyAObL7SjIDcjKC2LoORMgJ10JHw0fPhJ+2juouOG18sXqif8+2xkuQkHKvH1DD07yhUWTUiZCCzqUV4xeBIGAQRzmu7RuKnQAO/sayxhiAvxVCVpkPVhBVzRe5trGjEwl0cEd6mXz8Iy4p6JyaQXOhvM8VhG2LSHkhYwBgQUkVNaBF7y3hyp0Dm8fnGaEGkA1IDp5WfW8FjgpVpM3Y9HI+Uob98uIlDrEmEsuyp/H1dDW6Q9HZHpdEcRNh+hrYqWKh2gDUbj1XlEf/PfcBsm+fV8OYeaSUbZHMvZ7hGbIKLBTo3AlbLvYTd75F4y6QM0/79QU1IL0vMu/VUIk1KWVzWl9C5nTdocuOCeurIaVNG259lN/4dJbnGDyE8AOdbAcpw4lrBUMrhEt8UaNqBhpbdUmZKYZZJMikZvkfu4sf1YoLhTrUch//rjdInrK7BVmuwgRIy2IZhUti3c83pt7RjwSNIzEkWXwqaE4mf/iTqI4yfjwGB+IwJE54bbpAbjFrXi/jT20mQH/v4qr+xmo9hSbbyOGb8jNA==
    AWS_SECRET_ACCESS_KEY: AgBQx/5F5jcqKIbhmlZbYSZSi7yYYBqk59wWMtqcBwPO67yLaSuCunJOyoLJ15+pJcSewO+GN+5qeSgh5adTvuEcrkjP2fJlrzM7NFbVioRSCU23na2NzKBSMDvawrYKHMxhbB/6EkqY4Vuk0dSEsOIgBecLwKFrQEN/kYv3Myj+TfJDeeCDIuntFBi25mHtgjZ1oR1dGGzyz8yqBXv3RWbtgngRydMO1hDlxqvXSOb/C7670hqLTcUHvlU0sA31x6RD0ifyRDgJ6iD1i9MPucI45XJhcq+ghDthNhiiDd8jneai4dmns6Z0R/RwmJL8y+dUlXKRCxpX6qJCPZ8py6nAAA9NmKssOJUGZu7tT5d850wLL/sI05UXbyKtD78b8QGWxdD++I62pN2yTDmRgCXil4khATNCS3d95vuxlJWzmBsZfs8BS9z7poo4oKIURCqC+0xWbISz8DyyVJ5vlxmlwJV+T38Xha0H5Ve+ix8nCHJiWluVXbvUw4jB7llXcUccVtmBgGkXF4NCJzmgN8mjEc7uv/FKn6MaSX/Q1tijnnBBe8XHfkW2el7vT1DDFCTbI4En67Zb97MJaVUsdWyallkcP4ITkgY9yV1GzNCGqsHiJEtCX+A06XCarsgrNevtP09gHuu82JVlbry7aWrHZ3mVdFqrdNdvQN9fqQXlB+HtaUpX1uBhj9DsaHPX2TK/M7V9QRjQB/MzDpsosg53pBunJZ/jRI5XyJXk3rlKQ4adePznGdYp
  template:
    metadata:
      name: image-updater-ecr
      namespace: argocd
