---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-credentials
  namespace: observability
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDO7wcqvaMhiOAqxApcjrm+5oR+2rEF5mXkC/5pKWYwmDT12QoI1uT/mGMCDbfrH74w3FvfxmUj07qjAQrwbVAeG9Ul1INAvO8oMjd9ZXCFvcse0fOoLfUDPvC3WxDNOmvzyjMcrQ9f9cnjvZ7GsmeIJXyrFDGvGriRxTBsHYEYBT/prTomDsv5MNfrwzT2HXp1hufTvL/XTVAdCLCr5zY/nr7K+lF2okKNvn/YNWwLuXrcZ5bvVvZPYYdeW+1BPyvKLYOYdbyuuU0MQRxG8bvmaeaUp4seN0aQz1Vw28KsfixPTG1FjmxGey6SIA/UFZDt0R4126OSOrVAhbD+HrYype3B8VsyIEcqYX0ZEzSZZkZz1/l8WgifOu9k8pldVMR8XnO0JpfS2FfewdKk9hbr8xu9cCuDjd52HRi6OdZC2WtHybtw4T7MM5/9dCIDkdg3PJfKNap1b26s712PfPVEmrtZhd94URlpl0WiQeVnh9gC2QjG+he4peUza6RGGat+c8y4PKZrW8dWW890VQtl6S882FAHPssDkdYWkI7rMp9gYcrPnsyzp2i/ZTwCmNvlNSsz4X4SueutIQ3/hNyEl47/ieZOKoMOK6prpqLli95j9IeWHamCc29zjb9g9ImFiedrddPQYtqoz1PCCCQcdPCqlwT68LRNis8avLoD3DJrPKHQ3MHep3aylYqHNZPjA2v9DhfCp20=
    AWS_SECRET_ACCESS_KEY: AgAZpHEN7/j/P5gA345tJJVsA0r5WP+U1KzuyadczeXghYjdhS0jj/QJRBvps8cI2PDhOf/k+ScNkLxEjW8QvVSDgnstnkPMiH1u8r5oHcFxkeFVaaWM8e7ajRbcR3gLzsx3clYpmN00ThDIvMJ3P+2sDf4FGVVPj8DwnNVdBjA4JwNgV8MuPN/rEOvR2+QeB3xSGRaVUsVOsG1MIBoQaGIEoqq6De/9OtVjipXl7e3R3tKLPUZ2rb0JoucMlhichzIjypYwtbALW7A44Dob5c/qfUg08llMc9izKxFxgMEbm9SUo6dSnK6l2exjbkPKxy44+6QXqUiHPGwlwe/7Jo6nYf5xocVuGAlNdzLBIi9tyfHig6zdroYEuF/ja7iVu/S+A3W8Kqmz2DM+Klakgw6yz1q3mn09jUW6t24lK4J0kiLqrpIsQfavzCutDeZ4eeaYegrzEFRQO+WWG2OFF5XMHjFVu3ewyd6mbB0hWDDYlPoIa66xM+58Yf23HMAorWBQ/UuGGppErZ1sBPQO1P5J+00+CxdJVSZVglREtwOM+fLucI+dQcMWpew7jhh0lWTOOxGR/jCdvgJp0DHY2++K1Eh93sx69UkpnXdIyWJ+lqsnQNJIIYKpcmijVborO+KViyvgZg4YIkAGsU492K4Xf/cmkOE+azy7MeqO/MnHW2uZynp2LostsXK+EX3BnJ7eDdolZdYeGjo=
  template:
    metadata:
      name: loki-s3-credentials
      namespace: observability
