---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mimir-minio-credentials
  namespace: observability
spec:
  encryptedData:
    MIMIR_S3_ACCESS_KEY_ID: AgB39GBw7Fp129c008tVnhQsvfTMMistallnUxhuCUorzbvwtcd02ZqVx3xTjBpRNAKQrwRQgIL4QhapAtVdOp+cStCXfLi5bFD6ocB0VLz02ypDuGtLUjXQl8FnJWQpQoFydBjDAifelUHzJ0Y8pJ/6qaf5JjEu7oJm2cPdaIpVQ3yD1MeaZislh82dDhakKnbDdx9jkVOr+VngSqqB2THuXfvWcH0vXlJG4HBufeayT9l217aIaTnIIHZj0WnkBOFwMQsfax+SA8r2v4xvEOPBHXmsgZ2ug8ZBeSOe7eRsHHKZBD9wD8n/e/YVCFfrg+aIPy8FsQM4hWLU1zMUD9DLOYPDnaU3Ef7+HnM1Vvpt49UEdF3Ij5c8Z7u0VRVKUVUOZQ2HLfMcjCI25do8HwgCtWoaAfhgNUxh8t+2gz7DEl17oKPU3ZmBCuwWNoEH+wvhn8U1QeCKnaljgzJhZrpj+CQBbGZvTqgn7kmsten8KF8C8CmWlGaX3q88pjXYXax9UNJkDopu55lEMt56/MJYWcA+forib0yOESG0APJGhdS1LTQ+UOkrCOSm41mdAGSaH2U5qUUEBXhwPyZlWdDB//4KMgbroPcyzkbSA+EjUZUlr4Pz6We+s+697rBNLqKwa50VeJ4wlRxTqEXcvdd9RD4SKc01boGWW+EwXw2w2a4gRnMjYOFwq25Aq0CNAJYnPTlf8d9ObvY=
    MIMIR_S3_SECRET_ACCESS_KEY: AgA3VhtmihTbit7va27NirQwRhJ7vgNolEqVhOEgEKwtHSDvsr1vAoYaaQS9sdLMQEzsCVzNWNu8P/c9UkWtxUTkHGamaAxCnOvawCIIFkJngdykAIKldVv5d9OxhFGO9gPb/+BblUYGjOHfx8gKoTvRpCl/5a37Ib9Et7Wjma4c5xkhfvaw0J5ZpmPpEgt/DdZy2e99cM309WzV8S9L6uZE6Ux45b18PM6kjaQc2M/gbRrcX/YxY7iFtgfyK46jn9eGVkzvdzbMqGbXioBLCoh1NuCISi/EdiwFu2XFHTJTNevwq2qfTDDS1iUclXLmU+gwDoFYkEAbmtLmjsmoi+LzsitOr258gTRVFA4BOBKFB3QvNrcVj4KUpqrBAsiVetsJugIbgUNXnXR4xcq2UJ937ppnT48KpoZEzvs79UlNw25u/GUL7JThCR4cEAwwFw5fqzc4PiWcbVn+9wn5Jh0eVPRpc+HK26ikzuqcfbw+6o5mIPnmSjaRsZP0WKCbyQ4A85UunAOXYJRWISE0Dh6wIMjF0f85L6zdiSUz1H6Au+vsmxEGkWNdyaeqO0Lf9MzlGOvpG9XzGu+5gCqOOvyG6ac49bZPKi4Kd3NlwLsa0Lfz77WG7tiQIKYH/ScISGV4d9IXocQYAqa4JMuj/EmFVkOcf6M3Ki9kNQ07jVAOsSDiiYGotA5k0DaS4yuOOO5i/AjI/PPO9U4=
  template:
    metadata:
      name: mimir-minio-credentials
      namespace: observability
