---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-secret
  namespace: observability
spec:
  encryptedData:
    rootPassword: AgBROSPTK8s4ehZw22yqdZuNQR8IhDyk0WB5AAHFwfmGrsqaptWoexErAxJtGqitDZIG756Ph37g82Y0sxpp48KORJecoQ0GMIOVT1itPy63LGiqbjH2yTqse2AZcvz5BruCoRSQX18WACqX+y/wkQ2j4xsne1Jw49Dzr1TkmSmPNq5wYkwEtscYgfheXxhtq+WWOAzFfQPSpkwF1NkvKh8Ze6oJ3wzhTAQSxNpMgxyRDM+Ke4F/T/npYLtVyJb7IKiVCD8DijUbFVlR9ACQPFGAhWDdbsUjq4cqpPtRDpbIboXMTfP5ruYIgvblBm6DJtb9pyMvmbNZljxHYvXm1O4Q10BKIgXukViNY8oq1fhablKHNA1f0qHVythWCAcN/fgFId3IzhaxCm9pijrDZhQ3OGIEV4TSMF114I3zfoR05etJk6L1A3BuBImwzIZfuKDfc5adpJu5K8f0nKDXoICSvbCCH4S+6cMaoB8c2/pKd6wLPCrp1jbvl0lpxkqGoOF7aLCe1y3QakkNPn67EO+zlxhFUlmp2eX4e2dPamqgYjDOIHK1dlsB/tfrFq/K7YavB9GC6WAVzZ32e3M2zkzp/qhaEwWTaFLSERhF2kLq2bG308asYNjRr2bvocRMZFLHKAhdP3bgEd/r8qoZFk4RfgijreAqi74XGceahS0mUJClrGUPGHdqfJg8tGZ1z15CjMrwIU1lyY8=
    rootUser: AgBzbHfD7GIRkIuxos5kWMnIbmIdPZV2U+Q9283iA00coIT8JHTZL7WbSeQCa89gYapjb+t+yWCw2IIJ+HLiy2Od3B6jt5xgth05FAFoAs+1DAq2uzNCHDyWxP8kPDtP8CXu9e3DS0NpTmg2Dtz+El06tIU2JhpeUTTpvV0gH4qh08m+q8cM6nTIJfdSvlVVhixjAOuOfbF4wA7Pm5hj8kActH3Fnjs4QInJoi/7qPEQdERtJb8FwUF4AqpjVi3O3VAIBmMH6XJd25+X5xd1J+2NwRC+ZvJlwj3arPB6Xbf6zwf7tnAdp0TeBn5Hv5+Vkfj6e34RtdVbckgpIY0cRBI6MjaB+hMlLjsF1Ei6KOU+gYkiwRrRlvP4LLkuBXUhToQjuA0ignJNofXl6NSrkbnCeqVvzWMf3lWo3cPOktEBlI7c4HKtfNxeyW6yUYNSp0wETY0wp4wREHRz23l5WjVrtuppROZ2kBA8uiwJ+4LFiPDejz3i50fhJr6pnaUjHwOAILmbRi+Jfvhzl0Etxhz60SOjf5r6VJj6z6OFoSEUh0Kgkd0GE+05e1TZO05Mx36R8jXVVkECb35oAbXOkzw4/Uj2y9ajf7wf/H875oJCFBJKICeiNj6+G34I9ODPrJsOp02YkPeBgth80SmrSuot88MxC1M4DAylhJZGDikuRjB6wkJ7HO8G11rqtSi6Rt29NiQM+g==
  template:
    metadata:
      name: minio-root-secret
      namespace: observability
