---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: queue-secrets
  namespace: app
spec:
  encryptedData:
    REDIS_PASSWORD: AgCCOwJHFEhxycEv6121y53osexj1hRZVkdUl0U6aQ1jjIbSEt/XP0jD+u1/u85w4PgSg2oqepOUeXiIXZ6ZMLKYuwLZt7h7B+flfI+y4dGdiQFqfQuMYLURCpp6/rjtgjNPRt0wkOC45JjbaGBDUm6olgWbZ+GvNyGVCBUtWm7komR6wh//NW8x9JjsZsu4FGmzVnKz76X9fNRvyeTWyPRuNxFO08ZzNsqTLGbzl0P5ZZ0ttP/0BjzWmpATwVvgCLBktMcUdQsP20Nqw2R9NMVwincug9mknKvt3wUC9QITrG4KbI5Z5XNpfNe3afeUK3ciWYciffXjBY3fWW38mteKu/L/NADGB44Mue1lj9/BWmuJfJ4zlDk2UtE5pFMr0OB+NvtUnmFU7a0vCoGAVQ8F4eL87jhCffLDnlcoR81kALYrxPahs34AbAQj9L4twVwHuSsx6FenWlZhJ55KRSaK/SO3Sbpibdb6LPEz8Kg3zuOx76JOQ8yBrHAYyzkav1h5qpSehfPdHMoEb/JIiELb6qwFV8VNFhHNhVHLAJU9IRUpqgDxW6CB/IFFgkYjVlRaD/QKwCgf5vh39LJJUY2fzgjloG/M+1R1hfkYOa8DXmFedWeRVEeEuFGCeuTDhoHxFyEuVr1XoLdTMGrKNXn8+0Tn7QyrLAYwZX/9zbUpvE7/dObBB37HH6w5BsLhePlKrX54TEbo+WE=
  template:
    metadata:
      name: queue-secrets
      namespace: app
