---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: data
spec:
  encryptedData:
    redis-password: AgBtUIeVKW+9zUBMlDPMrzHP2xETcdylz4Ag97ZZgS4cPNWlGmrpflKBfb/qd8jHMdYX1eYV5qPF4AnetOEzc6JBti89r6rhabNFFwViuthayCO3rhXbqN8oprKxXwyDuJDJLifgsOb5UOSth00m02Lztu0rMncs2CjJTJUrmKQJlkPdx5g63/guLFz5LbAXXaNZXB7DZLS7pxx0/+GGA+qo490YTemGdDwNdK6QuMqcWRD4168sjYLK3bgg+qz5UcHiLJnZzp6JhRX9OA1nG9SlLlUakwVXTUaE77sDPJ8EyQUFD27Ne84bkvSq8BdvzDqbG9wZlP7l+HDb9ZC8auktlk9b9zXJw83XrQNhMD+0pnNNutflpOz27Itm0iK7HGYmgBghegAktJ/NGTlctFuPGZZ8uvR/2cdRnZPPVgtjGewm3lYZDVdH1o5qjDfAzPC2gIBOfH/FumivpofZeDJfRiE+2GDBFFmuPhdif8GqquXieKVwF6qtq9kukyxCpmM2fCmBAh563FjE+kIm1Dph298hWQu8ctockbdbQw7FIxRUnLNCx1H7CFIi6CMB4a7XWhXchifNW+hnVA5eqcSewxGjT8ZJx4Xr2AFSr4wPL5UdmrssS4EnK+e1dK++sTPnrBokIvhAGvefrIZF7eokWO5z8zmoIHNgGqThN6F/JQi/TKYjEFe+EhlYnfhkJFEgMQGKNdZAGis=
  template:
    metadata:
      name: redis-secret
      namespace: data
