{{- if and .Values.sealedSecret.enabled .Values.sealedSecret.encryptedPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
spec:
  encryptedData:
    {{ .Values.sealedSecret.key }}: {{ .Values.sealedSecret.encryptedPassword }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.name }}
    type: Opaque
{{- end }}
